theme: jekyll-theme-minimal
title: Doan Phan Resume
description: Full-stack developer with four years of experience in software development. Having a robust skill set encompassing both front-end and back-end technologies. Skilled in automated testing, improved code quality, system reliability, and team productivity.